post http://localhost:3003/api/login
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvc2h5ZWU3NzciLCJpZCI6IjYyNTliMDc5ZjJjNzU2ODkxNzg4YjI4ZiIsImlhdCI6MTY1MDA0NTE2MX0.i7l-x8HVa1xocAJ3ZFRjy2v5PMmibFHpF1kkQhaAoQM

{
    "username": "joshyee777",
    "password": "password123"
}